In [3]:
import numpy as np


In [10]:
##one dimensional array###

a = np.array([0,1,2,3,4,5])

In [11]:
a.ndim

1

In [12]:
a.shape

(6,)

In [17]:
## transform this array in to a 2D matrix

b = a.reshape(3,2)
b.shape


(3, 2)

In [18]:
a*2

array([ 0,  2,  4,  6,  8, 10])

In [19]:
a**2

array([ 0,  1,  4,  9, 16, 25])

In [21]:
c = [1,2,3,4,5]
c*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [23]:
a[np.array([1,2,3,4,5])]

array([1, 2, 3, 4, 5])

In [24]:
a>4

array([False, False, False, False, False,  True], dtype=bool)

In [26]:
a = '2017-03-24'
print(type(a))

<class 'str'>


In [53]:
from datetime import datetime
from dateutil.parser import parse
b= datetime.strptime(a,'%Y-%m-%d').strftime('%d/%m/%Y')
print(b)


#c= datetime.strptime(b,'%d/%m/%Y')





24/03/2017
